/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Wed Aug 28 23:37:53 2019. */

#include "OVTSProto.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t custom_struct_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, custom_struct, key, key, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, custom_struct, value, key, 0),
    PB_LAST_FIELD
};

const pb_field_t device_timer_struct_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, device_timer_struct, network_send, network_send, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, device_timer_struct, network_receive, network_send, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, device_timer_struct, sms_send, network_receive, 0),
    PB_LAST_FIELD
};

const pb_field_t device_data_select_struct_fields[8] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, device_data_select_struct, gps_enable, gps_enable, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, device_data_select_struct, imu_enable, gps_enable, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, device_data_select_struct, relay_enable, imu_enable, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, device_data_select_struct, input_sensor_enable, relay_enable, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, device_data_select_struct, sim_balance_enable, input_sensor_enable, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, device_data_select_struct, battery_enable, sim_balance_enable, 0),
    PB_FIELD(  7, INT32   , REQUIRED, STATIC  , OTHER, device_data_select_struct, signal_quality_enable, battery_enable, 0),
    PB_LAST_FIELD
};

const pb_field_t device_params_struct_fields[4] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, device_params_struct, timer, timer, &device_timer_struct_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, device_params_struct, data_select, timer, &device_data_select_struct_fields),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, device_params_struct, connection_type, data_select, 0),
    PB_LAST_FIELD
};

const pb_field_t center_address_struct_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, center_address_struct, device_data_url, device_data_url, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, center_address_struct, center_commands_url, device_data_url, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, center_address_struct, device_report_url, center_commands_url, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, center_address_struct, ping_url, device_report_url, 0),
    PB_LAST_FIELD
};

const pb_field_t center_params_struct_fields[5] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, center_params_struct, center_address, center_address, &center_address_struct_fields),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, center_params_struct, number1, center_address, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, center_params_struct, number2, number1, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, center_params_struct, number3, number2, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceData_fields[13] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceData, device_id, device_id, 0),
    PB_FIELD(  2, INT64   , REQUIRED, STATIC  , OTHER, DeviceData, time, device_id, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceData, gps_data, time, &DeviceData_gps_data_struct_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceData, imu_data, gps_data, &DeviceData_imu_data_struct_fields),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, DeviceData, relay, imu_data, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, DeviceData, input_sensor, relay, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, DeviceData, sim_balance, input_sensor, 0),
    PB_FIELD(  8, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceData, battery_data, sim_balance, &DeviceData_battery_struct_fields),
    PB_FIELD(  9, INT32   , OPTIONAL, STATIC  , OTHER, DeviceData, signal_quality, battery_data, 0),
    PB_FIELD( 10, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceData, center_params, signal_quality, &center_params_struct_fields),
    PB_FIELD( 11, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceData, device_params, center_params, &device_params_struct_fields),
    PB_FIELD( 12, MESSAGE , REPEATED, STATIC  , OTHER, DeviceData, custom_field, device_params, &custom_struct_fields),
    PB_LAST_FIELD
};

const pb_field_t DeviceData_imu_data_struct_fields[10] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, DeviceData_imu_data_struct, ax, ax, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, DeviceData_imu_data_struct, ay, ax, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, DeviceData_imu_data_struct, az, ay, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, DeviceData_imu_data_struct, gx, az, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, DeviceData_imu_data_struct, gy, gx, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, DeviceData_imu_data_struct, gz, gy, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, DeviceData_imu_data_struct, mx, gz, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, DeviceData_imu_data_struct, my, mx, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, DeviceData_imu_data_struct, mz, my, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceData_gps_data_struct_fields[7] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, DeviceData_gps_data_struct, lat, lat, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, DeviceData_gps_data_struct, lng, lat, 0),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, DeviceData_gps_data_struct, speed, lng, 0),
    PB_FIELD(  4, DOUBLE  , REQUIRED, STATIC  , OTHER, DeviceData_gps_data_struct, altitude, speed, 0),
    PB_FIELD(  5, DOUBLE  , REQUIRED, STATIC  , OTHER, DeviceData_gps_data_struct, course, altitude, 0),
    PB_FIELD(  6, DOUBLE  , REQUIRED, STATIC  , OTHER, DeviceData_gps_data_struct, hdop, course, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceData_battery_struct_fields[3] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, DeviceData_battery_struct, capacity, capacity, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceData_battery_struct, plugged, capacity, 0),
    PB_LAST_FIELD
};

const pb_field_t CenterCommands_fields[8] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, CenterCommands, device_id, device_id, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, CenterCommands, set_center_params, device_id, &CenterCommands_set_center_params_struct_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, CenterCommands, device_params, set_center_params, &device_params_struct_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, CenterCommands, device_report, device_params, &CenterCommands_report_struct_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, CenterCommands, device_sleep, device_report, &CenterCommands_sleep_struct_fields),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, CenterCommands, relay, device_sleep, 0),
    PB_FIELD(  7, MESSAGE , REPEATED, STATIC  , OTHER, CenterCommands, custom_field, relay, &custom_struct_fields),
    PB_LAST_FIELD
};

const pb_field_t CenterCommands_report_struct_fields[3] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, CenterCommands_report_struct, start, start, 0),
    PB_FIELD(  2, INT64   , REQUIRED, STATIC  , OTHER, CenterCommands_report_struct, end, start, 0),
    PB_LAST_FIELD
};

const pb_field_t CenterCommands_sleep_struct_fields[3] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, CenterCommands_sleep_struct, start, start, 0),
    PB_FIELD(  2, INT64   , REQUIRED, STATIC  , OTHER, CenterCommands_sleep_struct, end, start, 0),
    PB_LAST_FIELD
};

const pb_field_t CenterCommands_set_center_params_struct_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, CenterCommands_set_center_params_struct, key, key, 0),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, CenterCommands_set_center_params_struct, center_params, key, &center_params_struct_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(device_params_struct, timer) < 65536 && pb_membersize(device_params_struct, data_select) < 65536 && pb_membersize(center_params_struct, center_address) < 65536 && pb_membersize(DeviceData, gps_data) < 65536 && pb_membersize(DeviceData, imu_data) < 65536 && pb_membersize(DeviceData, battery_data) < 65536 && pb_membersize(DeviceData, center_params) < 65536 && pb_membersize(DeviceData, device_params) < 65536 && pb_membersize(DeviceData, custom_field[0]) < 65536 && pb_membersize(CenterCommands, set_center_params) < 65536 && pb_membersize(CenterCommands, device_params) < 65536 && pb_membersize(CenterCommands, device_report) < 65536 && pb_membersize(CenterCommands, device_sleep) < 65536 && pb_membersize(CenterCommands, custom_field[0]) < 65536 && pb_membersize(CenterCommands_set_center_params_struct, center_params) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_custom_struct_device_timer_struct_device_data_select_struct_device_params_struct_center_address_struct_center_params_struct_DeviceData_DeviceData_imu_data_struct_DeviceData_gps_data_struct_DeviceData_battery_struct_CenterCommands_CenterCommands_report_struct_CenterCommands_sleep_struct_CenterCommands_set_center_params_struct)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for custom_struct.value is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
